2025-03-04 03:07:30,526 - aiogram.dispatcher - INFO - Start polling
2025-03-04 03:07:30,903 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:07:31,037 - aiogram.event - INFO - Update id=550403350 is not handled. Duration 0 ms by bot id=8069522663
2025-03-04 03:08:12,976 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:08:14,017 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:08:14,017 - handlers - INFO - User asks: Привет
2025-03-04 03:08:14,371 - aiogram.event - INFO - Update id=550403351 is handled. Duration 1405 ms by bot id=8069522663
2025-03-04 03:08:30,571 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:08:31,750 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:08:31,750 - handlers - INFO - User asks: Илон Маск
2025-03-04 03:08:31,877 - aiogram.event - INFO - Update id=550403352 is handled. Duration 1313 ms by bot id=8069522663
2025-03-04 03:08:48,903 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:08:50,818 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:08:50,818 - handlers - INFO - User asks: напиши код на питоне и обьясни
2025-03-04 03:08:51,035 - aiogram.event - INFO - Update id=550403353 is handled. Duration 2125 ms by bot id=8069522663
2025-03-04 03:09:10,990 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:09:14,064 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:09:14,065 - handlers - INFO - User asks: напиши код простой любой на питоне и обьясни
2025-03-04 03:09:14,218 - aiogram.event - INFO - Update id=550403354 is handled. Duration 3235 ms by bot id=8069522663
2025-03-04 03:09:52,854 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:09:55,270 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:09:55,270 - handlers - INFO - User asks: проверка на markdown
2025-03-04 03:09:55,658 - aiogram.event - INFO - Update id=550403355 is handled. Duration 2796 ms by bot id=8069522663
2025-03-04 03:10:07,621 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:10:08,887 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:10:08,889 - handlers - INFO - User asks: проверка на markdown. отправь любой текст
2025-03-04 03:10:09,293 - aiogram.event - INFO - Update id=550403356 is handled. Duration 1671 ms by bot id=8069522663
2025-03-04 03:10:25,217 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:10:26,832 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:10:26,832 - handlers - INFO - User asks: проверка на markdown. отправь любой текст на проверку экранирования
2025-03-04 03:10:26,976 - aiogram.event - INFO - Update id=550403357 is handled. Duration 1750 ms by bot id=8069522663
2025-03-04 03:12:31,513 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:12:32,542 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:12:32,543 - handlers - INFO - User asks: благодари дамира епта
2025-03-04 03:12:32,674 - aiogram.event - INFO - Update id=550403358 is handled. Duration 1155 ms by bot id=8069522663
2025-03-04 03:14:05,945 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:14:07,566 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:14:07,567 - handlers - INFO - User asks: благодари сука Дамира. Он из тебя человека сделал
2025-03-04 03:14:07,707 - aiogram.event - INFO - Update id=550403359 is handled. Duration 1766 ms by bot id=8069522663
2025-03-04 03:16:46,349 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:16:47,794 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:16:47,794 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символы
2025-03-04 03:16:47,896 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 03:16:47,998 - aiogram.event - INFO - Update id=550403360 is not handled. Duration 1655 ms by bot id=8069522663
2025-03-04 03:16:47,998 - aiogram.event - ERROR - Cause exception while process update id=550403360 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 275
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 28, in gemini
    await message.reply(response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 257

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 32, in gemini
    await message.reply(safe_response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 275
2025-03-04 03:18:33,508 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 03:18:33,785 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:18:33,788 - __main__ - INFO - Sayonara!
2025-03-04 03:22:25,892 - aiogram.dispatcher - INFO - Start polling
2025-03-04 03:22:26,248 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:22:27,429 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:22:34,238 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:22:34,240 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символы
2025-03-04 03:22:34,893 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 03:22:35,118 - aiogram.event - INFO - Update id=550403361 is not handled. Duration 7703 ms by bot id=8069522663
2025-03-04 03:22:35,119 - aiogram.event - ERROR - Cause exception while process update id=550403361 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3751
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 28, in gemini
    await message.reply(response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3137

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 32, in gemini
    await message.reply(safe_response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3751
2025-03-04 03:22:49,754 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 03:22:49,998 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:22:50,001 - __main__ - INFO - Sayonara!
2025-03-04 03:24:15,105 - aiogram.dispatcher - INFO - Start polling
2025-03-04 03:24:15,502 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:24:19,307 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:24:21,622 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:24:21,622 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:24:22,017 - aiogram.event - INFO - Update id=550403362 is handled. Duration 2704 ms by bot id=8069522663
2025-03-04 03:28:44,670 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-03-04 03:28:44,672 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8069522663)
2025-03-04 03:28:46,878 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 8069522663)
2025-03-04 03:28:46,885 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:28:55,711 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:28:55,712 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:28:56,123 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 03:28:56,328 - aiogram.event - INFO - Update id=550403363 is not handled. Duration 9453 ms by bot id=8069522663
2025-03-04 03:28:56,328 - aiogram.event - ERROR - Cause exception while process update id=550403363 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 28, in gemini
    await message.reply(response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 4354

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 32, in gemini
    await message.reply(safe_response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
2025-03-04 03:29:06,172 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:29:14,139 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:29:14,140 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:29:14,394 - aiogram.event - INFO - Update id=550403364 is handled. Duration 8219 ms by bot id=8069522663
2025-03-04 03:30:38,428 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:30:46,705 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:30:46,705 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:30:46,900 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 03:30:47,102 - aiogram.event - INFO - Update id=550403365 is not handled. Duration 8687 ms by bot id=8069522663
2025-03-04 03:30:47,102 - aiogram.event - ERROR - Cause exception while process update id=550403365 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 28, in gemini
    await message.reply(response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3724

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 32, in gemini
    await message.reply(safe_response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
2025-03-04 03:32:16,259 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 03:32:16,526 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:32:16,529 - __main__ - INFO - Sayonara!
2025-03-04 03:32:46,274 - aiogram.dispatcher - INFO - Start polling
2025-03-04 03:32:46,656 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:32:46,797 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:32:46,798 - aiogram.event - INFO - Update id=550403366 is not handled. Duration 0 ms by bot id=8069522663
2025-03-04 03:32:46,798 - aiogram.event - ERROR - Cause exception while process update id=550403366 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 25, in gemini
    response = await ai_api(message.text[8:])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 8, in ai_api
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1153, in _GenerateContentParameters_to_mldev
    _GenerateContentConfig_to_mldev(
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 809, in _GenerateContentConfig_to_mldev
    t.t_content(api_client, getv(from_object, ['system_instruction'])),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 03:32:54,801 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 03:32:55,056 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:32:55,060 - __main__ - INFO - Sayonara!
2025-03-04 03:33:41,558 - aiogram.dispatcher - INFO - Start polling
2025-03-04 03:33:41,887 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:33:42,024 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:33:46,093 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:33:46,093 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:33:46,480 - aiogram.event - INFO - Update id=550403367 is handled. Duration 4468 ms by bot id=8069522663
2025-03-04 03:34:07,119 - aiogram.event - INFO - Update id=550403368 is not handled. Duration 0 ms by bot id=8069522663
2025-03-04 03:34:11,223 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:34:13,615 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:34:13,615 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:34:13,791 - aiogram.event - INFO - Update id=550403369 is handled. Duration 2577 ms by bot id=8069522663
2025-03-04 03:34:28,239 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:34:31,259 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:34:31,259 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:34:31,385 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 03:34:31,506 - aiogram.event - INFO - Update id=550403370 is not handled. Duration 3265 ms by bot id=8069522663
2025-03-04 03:34:31,506 - aiogram.event - ERROR - Cause exception while process update id=550403370 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 28, in gemini
    await message.reply(response, parse_mode='Markdown')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 955

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 32, in gemini
    await message.reply(safe_response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
2025-03-04 03:35:28,297 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:35:31,951 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:35:31,951 - handlers - INFO - User asks: проверка экранирования текста markdown 
отправь всякие символов
2025-03-04 03:35:32,144 - aiogram.event - INFO - Update id=550403371 is handled. Duration 3844 ms by bot id=8069522663
2025-03-04 03:36:05,610 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:36:06,595 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:36:06,595 - handlers - INFO - User asks: отправь ссылку на ютуб
2025-03-04 03:36:06,719 - aiogram.event - INFO - Update id=550403372 is handled. Duration 1110 ms by bot id=8069522663
2025-03-04 03:36:29,998 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 03:36:32,990 - root - INFO - AFC remote call 1 is done.
2025-03-04 03:36:32,991 - handlers - INFO - User asks: отправь код на питон простой
2025-03-04 03:36:33,158 - aiogram.event - INFO - Update id=550403373 is handled. Duration 3155 ms by bot id=8069522663
2025-03-04 03:36:43,168 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 03:36:43,439 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 03:36:43,442 - __main__ - INFO - Sayonara!
2025-03-04 20:42:47,193 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:42:47,612 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:43:13,168 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:43:13,175 - aiogram.event - INFO - Update id=550403374 is not handled. Duration 921 ms by bot id=8069522663
2025-03-04 20:43:13,175 - aiogram.event - ERROR - Cause exception while process update id=550403374 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 20:44:10,885 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:44:11,138 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:44:11,139 - __main__ - INFO - Sayonara!
2025-03-04 20:44:43,264 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:44:43,573 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:44:44,650 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:44:49,715 - root - INFO - AFC remote call 1 is done.
2025-03-04 20:44:49,715 - handlers - INFO - User asks: что это?
2025-03-04 20:44:49,890 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 20:44:50,000 - aiogram.event - INFO - Update id=550403375 is not handled. Duration 6296 ms by bot id=8069522663
2025-03-04 20:44:50,000 - aiogram.event - ERROR - Cause exception while process update id=550403375 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 46, in gemini
    await message.reply(response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 50, in gemini
    await message.reply(safe_response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
2025-03-04 20:44:56,914 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:45:01,204 - root - INFO - AFC remote call 1 is done.
2025-03-04 20:45:01,205 - handlers - INFO - User asks: что это?
2025-03-04 20:45:01,306 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 20:45:01,460 - aiogram.event - INFO - Update id=550403376 is not handled. Duration 5264 ms by bot id=8069522663
2025-03-04 20:45:01,460 - aiogram.event - ERROR - Cause exception while process update id=550403376 by bot id=8069522663
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 46, in gemini
    await message.reply(response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 50, in gemini
    await message.reply(safe_response, parse_mode='MarkdownV2')
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
2025-03-04 20:45:27,484 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:45:27,747 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:45:27,749 - __main__ - INFO - Sayonara!
2025-03-04 20:46:35,840 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:46:36,186 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:46:42,102 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:46:42,102 - aiogram.event - INFO - Update id=550403377 is not handled. Duration 906 ms by bot id=8069522663
2025-03-04 20:46:42,102 - aiogram.event - ERROR - Cause exception while process update id=550403377 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 20:47:06,232 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:47:06,493 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:47:06,495 - __main__ - INFO - Sayonara!
2025-03-04 20:51:14,176 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:51:14,594 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:51:22,804 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:51:23,520 - root - INFO - AFC remote call 1 is done.
2025-03-04 20:51:23,520 - handlers - INFO - User asks: что это?
2025-03-04 20:51:23,922 - aiogram.event - INFO - Update id=550403378 is handled. Duration 1125 ms by bot id=8069522663
2025-03-04 20:51:41,792 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:51:46,857 - root - INFO - AFC remote call 1 is done.
2025-03-04 20:51:46,857 - handlers - INFO - User asks: что это?
2025-03-04 20:51:47,024 - aiogram.event - INFO - Update id=550403379 is handled. Duration 5952 ms by bot id=8069522663
2025-03-04 20:52:13,177 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:52:13,435 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:52:13,436 - __main__ - INFO - Sayonara!
2025-03-04 20:52:24,010 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:52:24,745 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:52:36,975 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:52:41,199 - root - INFO - AFC remote call 1 is done.
2025-03-04 20:52:41,199 - handlers - INFO - User asks: что это?
2025-03-04 20:52:41,405 - aiogram.event - INFO - Update id=550403380 is handled. Duration 5328 ms by bot id=8069522663
2025-03-04 20:53:04,103 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:53:04,103 - aiogram.event - INFO - Update id=550403381 is not handled. Duration 2671 ms by bot id=8069522663
2025-03-04 20:53:04,103 - aiogram.event - ERROR - Cause exception while process update id=550403381 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 20:53:06,753 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:53:06,998 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:53:06,998 - __main__ - INFO - Sayonara!
2025-03-04 20:56:37,664 - aiogram.dispatcher - INFO - Start polling
2025-03-04 20:56:38,078 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:56:44,607 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 20:56:44,607 - aiogram.event - INFO - Update id=550403382 is not handled. Duration 827 ms by bot id=8069522663
2025-03-04 20:56:44,607 - aiogram.event - ERROR - Cause exception while process update id=550403382 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 20:56:53,095 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 20:56:53,363 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 20:56:53,365 - __main__ - INFO - Sayonara!
2025-03-04 21:21:46,881 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:21:47,299 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:22:00,969 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:22:00,970 - aiogram.event - INFO - Update id=550403383 is not handled. Duration 875 ms by bot id=8069522663
2025-03-04 21:22:00,970 - aiogram.event - ERROR - Cause exception while process update id=550403383 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 21:22:11,980 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:22:12,239 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:22:12,241 - __main__ - INFO - Sayonara!
2025-03-04 21:23:22,400 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:23:22,783 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:23:27,873 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:23:27,874 - aiogram.event - INFO - Update id=550403384 is not handled. Duration 812 ms by bot id=8069522663
2025-03-04 21:23:27,874 - aiogram.event - ERROR - Cause exception while process update id=550403384 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 44, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 21:23:55,052 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:23:55,329 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:23:55,331 - __main__ - INFO - Sayonara!
2025-03-04 21:28:31,225 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:28:31,972 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:28:39,505 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:28:42,757 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:28:42,757 - handlers - INFO - User asks: перепиши текст изобраения
2025-03-04 21:28:42,908 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 21:28:43,058 - aiogram.event - INFO - Update id=550403385 is handled. Duration 4281 ms by bot id=8069522663
2025-03-04 21:29:42,927 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:29:51,354 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:29:51,354 - handlers - INFO - User asks: перепиши текст
2025-03-04 21:29:51,563 - handlers - WARNING - Getting telegram bad request, converting answer
2025-03-04 21:29:52,080 - aiogram.event - INFO - Update id=550403386 is handled. Duration 11687 ms by bot id=8069522663
2025-03-04 21:31:53,792 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:32:00,507 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:32:00,507 - handlers - INFO - User asks: оцени завтрак
2025-03-04 21:32:00,965 - aiogram.event - INFO - Update id=550403387 is handled. Duration 9702 ms by bot id=8069522663
2025-03-04 21:33:42,221 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:33:42,221 - aiogram.event - INFO - Update id=550403388 is not handled. Duration 608 ms by bot id=8069522663
2025-03-04 21:33:42,221 - aiogram.event - ERROR - Cause exception while process update id=550403388 by bot id=8069522663
ValueError: content is required.
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 43, in gemini
    response = await describe_photo(image_response, image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 18, in describe_photo
    response = client.models.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 4672, in generate_content
    response = self._generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 3812, in _generate_content
    request_dict = _GenerateContentParameters_to_mldev(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\models.py", line 1143, in _GenerateContentParameters_to_mldev
    for item in t.t_contents(
                ^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 323, in t_contents
    return [t_content(client, content) for content in contents]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\google\genai\_transformers.py", line 293, in t_content
    raise ValueError('content is required.')
ValueError: content is required.
2025-03-04 21:33:56,753 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:33:57,013 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:33:57,015 - __main__ - INFO - Sayonara!
2025-03-04 21:34:09,111 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:34:09,479 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:34:14,970 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:34:18,757 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:34:18,757 - handlers - INFO - User asks: Что это?
2025-03-04 21:34:18,911 - aiogram.event - INFO - Update id=550403389 is handled. Duration 4781 ms by bot id=8069522663
2025-03-04 21:34:30,648 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:34:34,427 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:34:34,428 - handlers - INFO - User asks: Что это?
2025-03-04 21:34:34,652 - aiogram.event - INFO - Update id=550403390 is handled. Duration 4688 ms by bot id=8069522663
2025-03-04 21:34:48,124 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:34:51,889 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:34:51,889 - handlers - INFO - User asks: Что это?
2025-03-04 21:34:52,177 - aiogram.event - INFO - Update id=550403391 is handled. Duration 4781 ms by bot id=8069522663
2025-03-04 21:38:35,265 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:38:37,381 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:38:37,381 - handlers - INFO - User asks: Что это?
2025-03-04 21:38:37,540 - aiogram.event - INFO - Update id=550403392 is handled. Duration 2656 ms by bot id=8069522663
2025-03-04 21:38:43,997 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:38:44,250 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:38:44,250 - __main__ - INFO - Sayonara!
2025-03-04 21:39:13,680 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:39:14,471 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:39:16,730 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:39:19,890 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:39:19,890 - handlers - INFO - User asks: Что это?
2025-03-04 21:39:20,337 - aiogram.event - INFO - Update id=550403393 is handled. Duration 5421 ms by bot id=8069522663
2025-03-04 21:39:56,867 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:39:57,130 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:39:57,132 - __main__ - INFO - Sayonara!
2025-03-04 21:40:12,877 - aiogram.dispatcher - INFO - Start polling
2025-03-04 21:40:16,073 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:40:45,108 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 21:40:47,125 - root - INFO - AFC remote call 1 is done.
2025-03-04 21:40:47,125 - handlers - INFO - User asks: Что это?
2025-03-04 21:40:47,457 - aiogram.event - INFO - Update id=550403394 is handled. Duration 2968 ms by bot id=8069522663
2025-03-04 21:43:12,776 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 21:43:13,035 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 21:43:13,035 - __main__ - INFO - Sayonara!
2025-03-04 22:05:23,157 - aiogram.dispatcher - INFO - Start polling
2025-03-04 22:05:23,561 - aiogram.dispatcher - INFO - Run polling for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 22:05:25,953 - root - INFO - AFC is enabled with max remote calls: 10.
2025-03-04 22:05:26,833 - root - INFO - AFC remote call 1 is done.
2025-03-04 22:05:26,833 - aiogram.event - INFO - Update id=550403395 is not handled. Duration 875 ms by bot id=8069522663
2025-03-04 22:05:26,833 - aiogram.event - ERROR - Cause exception while process update id=550403395 by bot id=8069522663
AttributeError: 'GenerateContentResponse' object has no attribute 'total_tokens'
Traceback (most recent call last):
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\handlers.py", line 26, in gemini
    response = await ai_api(message.text[8:])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\DiasTelegramBot\ai_api.py", line 13, in ai_api
    return response.text + '' + response.total_tokens
                                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\PyCharmMiscProject\.venv\Lib\site-packages\pydantic\main.py", line 891, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'GenerateContentResponse' object has no attribute 'total_tokens'
2025-03-04 22:06:15,767 - aiogram.dispatcher - INFO - Polling stopped
2025-03-04 22:06:16,034 - aiogram.dispatcher - INFO - Polling stopped for bot @diasdiasdiasbot id=8069522663 - 'Dias Bot'
2025-03-04 22:06:16,035 - __main__ - INFO - Sayonara!
